name: Checking black

on:
  push:
    branches:
      - HarisTesing

jobs:
  run-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Installing black
        run:  pip install black
      
      - name: Installing flake8
        run: pip install flake8
      
      - name: Black check
        run: black <projects/Calculate_age/calculate.py>
